// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SenderCoordCore.Models
{
    public partial class Coords
    {
        public Guid CooRecordId { get; set; }
        public string CooImei { get; set; }
        public string CooLongitude { get; set; }
        public string CooLatitude { get; set; }
    }
}